import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const destinations = [
  {
    slug: 'pulau-penyengat',
    name: 'Pulau Penyengat',
    city: 'Tanjung Pinang',
    province: 'Kepulauan Riau',
    categoryName: 'Malay Heritage',
    shortDesc: 'Pulau bersejarah bekas pusat Kesultanan Riau-Lingga, tempat lahirnya bahasa Melayu standar dan sastra klasik Nusantara.',
    culturalMeaning: 'Pulau Penyengat adalah jantung peradaban Melayu. Di sini lahir bahasa Melayu yang menjadi dasar bahasa Indonesia modern. Pulau ini menyimpan warisan intelektual dan spiritual Kesultanan Riau-Lingga yang pernah menjadi pusat ilmu pengetahuan Melayu.',
    localHistory: 'Pada abad ke-19, Penyengat menjadi pusat pemerintahan Kesultanan Riau-Lingga. Raja Ali Haji, sastrawan Melayu terbesar, menulis Gurindam Pantun dan karya-karya monumental di sini. Masjid Raya Penyengat dibangun dengan putih telur sebagai perekat, menjadikannya ikon arsitektur unik.',
    malaysiaConnection: 'Kesultanan Riau-Lingga memiliki hubungan erat dengan Kesultanan Johor dan Melaka. Bahasa Melayu Riau menjadi standar bahasa Melayu yang digunakan di Malaysia hingga kini. Banyak tradisi, sastra, dan adat istiadat yang sama antara masyarakat Penyengat dengan masyarakat Johor-Riau.',
    localEtiquette: 'Kenakan pakaian sopan saat mengunjungi masjid. Hormati adat Melayu setempat. Jangan memotret tanpa izin di area privat. Gunakan bahasa yang santun.',
    coverImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Masjid_Raya_Penyengat.jpg/1280px-Masjid_Raya_Penyengat.jpg',
    latitude: 0.9267,
    longitude: 104.6467,
    nearestGateway: 'Bandara Raja Haji Fisabilillah, Tanjung Pinang',
    entryPoint: 'Malaysia → Ferry Batam → Ferry Tanjung Pinang → Perahu ke Pulau Penyengat',
    distanceKm: 5,
    accessLevel: 'EASY',
    weatherSummary: 'Tropis, suhu 25-33°C, hujan Jan-Mar',
    bestTimeToVisit: 'April-September (musim kemarau)',
    travelNotes: 'Ferry dari Batam ke Tanjung Pinang tersedia setiap hari. Dari pelabuhan, naik perahu tradisional ke Pulau Penyengat (10 menit).',
    safetyNotes: 'Patuhi aturan memasuki masjid. Gunakan pakaian sopan. Hati-hati saat naik turun perahu.',
  },
  {
    slug: 'istana-maimun-medan',
    name: 'Istana Maimun',
    city: 'Medan',
    province: 'Sumatera Utara',
    categoryName: 'Malay Heritage',
    shortDesc: 'Istana Kesultanan Deli yang megah, perpaduan arsitektur Melayu, Islam, Spanyol, dan India.',
    culturalMeaning: 'Istana Maimun adalah simbol kejayaan Kesultanan Deli. Arsitekturnya yang unik mencerminkan akulturasi budaya Melayu dengan pengaruh kolonial dan Islam, menunjukkan keterbukaan budaya Melayu pesisir.',
    localHistory: 'Dibangun tahun 1888 oleh Sultan Mahmud Al Rashid Perkasa Alamsyah. Istana ini menjadi pusat pemerintahan Kesultanan Deli yang menguasai perdagangan di pesisir timur Sumatera.',
    malaysiaConnection: 'Kesultanan Deli memiliki hubungan kekerabatan dengan Kesultanan Perak dan Selangor di Malaysia. Banyak keluarga kerajaan Deli yang menikah dengan bangsawan Melayu Semenanjung.',
    localEtiquette: 'Hormati adat Melayu Deli. Jangan masuk ke area privat istana tanpa izin. Foto diperbolehkan di area publik.',
    coverImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Istana_Maimun.jpg/1280px-Istana_Maimun.jpg',
    latitude: 3.5826,
    longitude: 98.6859,
    nearestGateway: 'Bandara Kualanamu, Medan',
    entryPoint: 'Malaysia → Flight/Penang-Medan atau Ferry Dumai-Melaka → Medan',
    distanceKm: 12,
    accessLevel: 'EASY',
    weatherSummary: 'Tropis, suhu 24-32°C, hujan Sep-Nov',
    bestTimeToVisit: 'Januari-Juli (musim kemarau)',
    travelNotes: 'Dari bandara Kualanamu, naik kereta atau taksi ke pusat Medan (1 jam). Istana Maimun berada di pusat kota.',
    safetyNotes: 'Waspadai copet di area wisata. Gunakan transportasi resmi.',
  },
  {
    slug: 'masjid-baiturrahman-aceh',
    name: 'Masjid Raya Baiturrahman',
    city: 'Banda Aceh',
    province: 'Aceh',
    categoryName: 'Islamic History',
    shortDesc: 'Masjid bersejarah simbol ketahanan Aceh, selamat dari tsunami 2004 dan menjadi ikon spiritual Nusantara.',
    culturalMeaning: 'Masjid ini adalah simbol spiritual dan ketahanan masyarakat Aceh. Bertahan dari tsunami 2004 menjadi bukti kekuatan spiritual dan arsitektur yang luar biasa.',
    localHistory: 'Dibangun tahun 1879 oleh Sultan Aceh. Masjid ini menjadi saksi perjuangan Aceh melawan Belanda dan tsunami dahsyat 2004 yang menghancurkan kota namun meninggalkan masjid ini berdiri.',
    malaysiaConnection: 'Aceh dan Malaysia memiliki ikatan sejarah Islam yang kuat. Banyak ulama Aceh yang belajar dan mengajar di Malaysia, dan sebaliknya. Tradisi Islam Aceh mempengaruhi perkembangan Islam di Semenanjung Melayu.',
    localEtiquette: 'Wajib berpakaian sopan dan menutup aurat. Wanita disarankan memakai jilbab. Hormati waktu sholat.',
    coverImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Masjid_Raya_Baiturrahman.jpg/1280px-Masjid_Raya_Baiturrahman.jpg',
    latitude: 5.5537,
    longitude: 95.3176,
    nearestGateway: 'Bandara Sultan Iskandar Muda, Banda Aceh',
    entryPoint: 'Malaysia → Flight KL/Penang-Banda Aceh',
    distanceKm: 15,
    accessLevel: 'EASY',
    weatherSummary: 'Tropis, suhu 24-32°C, hujan Okt-Jan',
    bestTimeToVisit: 'Februari-September',
    travelNotes: 'Bandara Sultan Iskandar Muda memiliki penerbangan dari KL dan Penang. Dari bandara ke pusat kota sekitar 30 menit.',
    safetyNotes: 'Patuhi aturan masjid. Hormati budaya lokal Aceh yang religius.',
  },
  {
    slug: 'kota-tua-jakarta',
    name: 'Kota Tua Jakarta',
    city: 'Jakarta',
    province: 'DKI Jakarta',
    categoryName: 'Colonial Era',
    shortDesc: 'Kawasan bersejarah peninggalan VOC Belanda, pusat perdagangan dan administrasi Hindia Belanda selama 300 tahun.',
    culturalMeaning: 'Kota Tua adalah saksi bisu sejarah kolonialisme di Nusantara. Arsitektur Belanda yang terawat menjadi museum hidup tentang masa lalu Jakarta sebagai Batavia.',
    localHistory: 'Didirikan oleh VOC tahun 1619 sebagai Batavia. Menjadi pusat administrasi dan perdagangan Hindia Belanda. Gedung-gedung kolonial seperti Museum Fatahillah, Museum Wayang, dan Sunda Kelapa masih berdiri.',
    malaysiaConnection: 'Batavia dan Melaka memiliki sejarah perdagangan yang saling terkait. Banyak pedagang Melayu yang berdagang antara Melaka dan Batavia. Hubungan dagang ini membentuk jaringan ekonomi maritim Nusantara.',
    localEtiquette: 'Jaga kebersihan. Jangan mencoret-coret bangunan bersejarah. Hormati pengunjung lain.',
    coverImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Museum_Fatahillah.jpg/1280px-Museum_Fatahillah.jpg',
    latitude: -6.1352,
    longitude: 106.8133,
    nearestGateway: 'Bandara Soekarno-Hatta, Jakarta',
    entryPoint: 'Malaysia → Flight KL-Jakarta',
    distanceKm: 25,
    accessLevel: 'EASY',
    weatherSummary: 'Tropis, suhu 25-33°C, hujan Nov-Mar',
    bestTimeToVisit: 'April-Oktober',
    travelNotes: 'Dari bandara, naik kereta bandara atau taksi ke Kota Tua (1-1.5 jam). Kawasan ini bisa dijelajahi dengan berjalan kaki.',
    safetyNotes: 'Waspadai copet. Gunakan transportasi resmi. Hati-hati saat menyeberang.',
  },
  {
    slug: 'keraton-yogyakarta',
    name: 'Keraton Yogyakarta',
    city: 'Yogyakarta',
    province: 'DI Yogyakarta',
    categoryName: 'Malay Heritage',
    shortDesc: 'Istana resmi Kesultanan Yogyakarta, pusat budaya Jawa yang masih aktif dan melestarikan tradisi kerajaan.',
    culturalMeaning: 'Keraton Yogyakarta adalah jantung budaya Jawa. Di sini tradisi, seni, dan filosofi Jawa dipertahankan selama berabad-abad. Merupakan simbol keberlanjutan budaya Nusantara.',
    localHistory: 'Didirikan tahun 1755 oleh Sultan Hamengkubuwono I setelah Perjanjian Giyanti. Keraton ini menjadi pusat pemerintahan dan budaya Kesultanan Yogyakarta yang masih bertahan hingga kini.',
    malaysiaConnection: 'Budaya Jawa memiliki pengaruh signifikan terhadap budaya Melayu, terutama dalam sastra, wayang, dan musik. Banyak elemen budaya Jawa yang diadopsi dan diadaptasi di kerajaan-kerajaan Melayu.',
    localEtiquette: 'Hormati adat Jawa. Jangan masuk ke area terlarang. Berpakaian sopan. Hormati upacara adat jika sedang berlangsung.',
    coverImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Keraton_Yogyakarta.jpg/1280px-Keraton_Yogyakarta.jpg',
    latitude: -7.8053,
    longitude: 110.3641,
    nearestGateway: 'Bandara Adisutjipto, Yogyakarta',
    entryPoint: 'Malaysia → Flight KL-Yogyakarta',
    distanceKm: 3,
    accessLevel: 'EASY',
    weatherSummary: 'Tropis, suhu 23-31°C, hujan Nov-Mar',
    bestTimeToVisit: 'April-Oktober',
    travelNotes: 'Keraton berada di pusat kota Yogyakarta. Mudah dijangkau dengan berjalan kaki dari Malioboro.',
    safetyNotes: 'Hormati upacara adat. Jangan memotret di area terlarang.',
  },
  {
    slug: 'tana-toraja',
    name: 'Tana Toraja',
    city: 'Makale',
    province: 'Sulawesi Selatan',
    categoryName: 'Traditional Village',
    shortDesc: 'Tanah suku Toraja dengan rumah adat Tongkonan, upacara pemakaman megah, dan tradisi unik yang masih lestari.',
    culturalMeaning: 'Tana Toraja adalah salah satu budaya paling unik di Indonesia. Upacara pemakaman Rambu Solo dan rumah Tongkonan menjadi simbol identitas dan spiritualitas masyarakat Toraja.',
    localHistory: 'Suku Toraja telah mendiami dataran tinggi Sulawesi Selatan selama berabad-abad. Tradisi megalitik dan animisme mereka bertahan hingga kini, berpadu dengan pengaruh Kristen dan Islam.',
    malaysiaConnection: 'Migrasi Toraja ke Malaysia (terutama Sabah dan Sarawak) telah terjadi selama dekade. Banyak pekerja Toraja yang berkontribusi pada pembangunan di Malaysia timur.',
    localEtiquette: 'Hormati upacara adat. Jangan masuk ke area pemakaman tanpa izin. Minta izin sebelum memotret. Hormati kepercayaan lokal.',
    coverImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Tongkonan_Toraja.jpg/1280px-Tongkonan_Toraja.jpg',
    latitude: -3.0638,
    longitude: 119.8478,
    nearestGateway: 'Bandara Toraja (Pongtiku), Makale',
    entryPoint: 'Malaysia → Flight KL-Makassar → Drive ke Toraja (8 jam)',
    distanceKm: 320,
    accessLevel: 'REMOTE',
    weatherSummary: 'Tropis dataran tinggi, suhu 18-28°C',
    bestTimeToVisit: 'Juni-September (upacara Rambu Solo sering diadakan)',
    travelNotes: 'Perjalanan dari Makassar ke Toraja memakan waktu 8-10 jam melalui jalan pegunungan. Disarankan sewa mobil dengan driver lokal.',
    safetyNotes: 'Hormati upacara adat. Jangan mengganggu prosesi pemakaman. Jalan pegunungan berkelok, hati-hati berkendara.',
  },
  {
    slug: 'candi-borobudur',
    name: 'Candi Borobudur',
    city: 'Magelang',
    province: 'Jawa Tengah',
    categoryName: 'Islamic History',
    shortDesc: 'Candi Buddha terbesar di dunia, warisan Dinasti Syailendra abad ke-9, mahakarya arsitektur dan spiritual Nusantara.',
    culturalMeaning: 'Borobudur adalah mahakarya spiritual dan arsitektur. Reliefnya menceritakan kisah Buddha dan kehidupan masyarakat Jawa kuno. Merupakan simbol toleransi dan kejayaan peradaban Nusantara.',
    localHistory: 'Dibangun sekitar tahun 800 M oleh Dinasti Syailendra. Ditinggalkan sekitar abad ke-14 dan ditemukan kembali tahun 1814 oleh Thomas Stamford Raffles. Dipugar berkali-kali dengan bantuan UNESCO.',
    malaysiaConnection: 'Dinasti Syailendra memiliki hubungan dengan kerajaan-kerajaan di Semenanjung Melayu. Pengaruh Buddha dan Hindu dari Nusantara menyebar ke seluruh Asia Tenggara maritim.',
    localEtiquette: 'Jangan memanjat candi. Hormati area spiritual. Jangan membuang sampah. Ikuti jalur yang ditentukan.',
    coverImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Borobudur_Temple.jpg/1280px-Borobudur_Temple.jpg',
    latitude: -7.6079,
    longitude: 110.2038,
    nearestGateway: 'Bandara Adisutjipto, Yogyakarta',
    entryPoint: 'Malaysia → Flight KL-Yogyakarta → Drive ke Borobudur (2.5 jam)',
    distanceKm: 40,
    accessLevel: 'EASY',
    weatherSummary: 'Tropis, suhu 22-31°C, hujan Nov-Mar',
    bestTimeToVisit: 'April-Oktober, sunrise sangat direkomendasikan',
    travelNotes: 'Dari Yogyakarta, naik bus atau sewa mobil ke Borobudur. Sunrise tour sangat populer, booking dari malam sebelumnya.',
    safetyNotes: 'Bawa air minum dan topi. Sunrise tour butuh persiapan dini. Hati-hati di tangga candi.',
  },
  {
    slug: 'kampung-pelangi-semarang',
    name: 'Kampung Pelangi',
    city: 'Semarang',
    province: 'Jawa Tengah',
    categoryName: 'Traditional Village',
    shortDesc: 'Kampung warna-warni yang menjadi simbol revitalisasi urban dan kreativitas masyarakat lokal.',
    culturalMeaning: 'Kampung Pelangi menunjukkan bagaimana kreativitas masyarakat dapat mengubah lingkungan kumuh menjadi destinasi wisata yang menarik dan membanggakan.',
    localHistory: 'Dulunya kawasan kumuh di Randusari, Semarang. Tahun 2017, pemerintah kota dan masyarakat berkolaborasi mengecat rumah-rumah dengan warna-warni, mengubahnya menjadi ikon wisata.',
    malaysiaConnection: 'Model revitalisasi kampung ini menginspirasi program serupa di Malaysia, seperti Kampung Baru di KL. Pertukaran ide urban revitalisasi antara Indonesia dan Malaysia terus berlangsung.',
    localEtiquette: 'Hormati privasi warga. Jangan masuk ke rumah tanpa izin. Jaga kebersihan.',
    coverImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Kampung_Pelangi_Semarang.jpg/1280px-Kampung_Pelangi_Semarang.jpg',
    latitude: -6.9932,
    longitude: 110.4203,
    nearestGateway: 'Bandara Ahmad Yani, Semarang',
    entryPoint: 'Malaysia → Flight KL-Semarang',
    distanceKm: 8,
    accessLevel: 'EASY',
    weatherSummary: 'Tropis, suhu 24-33°C, hujan Nov-Mar',
    bestTimeToVisit: 'April-Oktober',
    travelNotes: 'Dari bandara, naik taksi atau Grab ke Kampung Pelangi (30 menit). Kawasan ini kecil, bisa dijelajahi dalam 1-2 jam.',
    safetyNotes: 'Hormati privasi warga. Jangan memotret tanpa izin di area privat.',
  },
  {
    slug: 'benteng-vredeburg-yogyakarta',
    name: 'Benteng Vredeburg',
    city: 'Yogyakarta',
    province: 'DI Yogyakarta',
    categoryName: 'Colonial Era',
    shortDesc: 'Benteng Belanda abad ke-18 yang kini menjadi museum perjuangan bangsa Indonesia.',
    culturalMeaning: 'Vredeburg adalah simbol perlawanan terhadap kolonialisme. Dari benteng ini, Belanda mengontrol Kesultanan Yogyakarta, namun kini menjadi museum yang menceritakan perjuangan kemerdekaan.',
    localHistory: 'Dibangun tahun 1765 oleh Belanda atas permintaan Sultan Hamengkubuwono I. Awalnya bernama Fort Rustenburg, kemudian diganti menjadi Vredeburg setelah direnovasi.',
    malaysiaConnection: 'Sejarah kolonialisme Belanda dan Inggris di Nusantara memiliki paralel dengan sejarah kolonial di Malaysia. Banyak pelajaran bersama tentang perlawanan dan diplomasi.',
    localEtiquette: 'Hormati museum. Jangan menyentuh artefak. Ikuti aturan foto.',
    coverImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Benteng_Vredeburg.jpg/1280px-Benteng_Vredeburg.jpg',
    latitude: -7.8015,
    longitude: 110.3677,
    nearestGateway: 'Bandara Adisutjipto, Yogyakarta',
    entryPoint: 'Malaysia → Flight KL-Yogyakarta',
    distanceKm: 3,
    accessLevel: 'EASY',
    weatherSummary: 'Tropis, suhu 23-31°C, hujan Nov-Mar',
    bestTimeToVisit: 'April-Oktober',
    travelNotes: 'Berada di pusat kota Yogyakarta, dekat Keraton dan Malioboro. Bisa dijangkau dengan berjalan kaki.',
    safetyNotes: 'Hormati aturan museum. Jaga ketenangan.',
  },
  {
    slug: 'rumah-gadang-bukittinggi',
    name: 'Rumah Gadang Bukittinggi',
    city: 'Bukittinggi',
    province: 'Sumatera Barat',
    categoryName: 'Traditional Village',
    shortDesc: 'Rumah adat Minangkabau dengan atap gonjong yang ikonik, simbol budaya matrilineal terbesar di dunia.',
    culturalMeaning: 'Rumah Gadang adalah simbol budaya Minangkabau yang unik. Sistem matrilineal (garis keturunan perempuan) menjadi salah satu yang terbesar di dunia, menunjukkan keberagaman budaya Nusantara.',
    localHistory: 'Rumah Gadang telah menjadi ciri khas Minangkabau selama berabad-abad. Arsitektur gonjong (atap runcing) terinspirasi dari tanduk kerbau, yang juga menjadi asal nama "Minangkabau".',
    malaysiaConnection: 'Banyak orang Minangkabau yang merantau ke Malaysia (dikenal sebagai "Mande" atau "Urang Awak"). Kontribusi mereka dalam kuliner (rendang, nasi padang) sangat terasa di Malaysia.',
    localEtiquette: 'Hormati adat Minangkabau. Jangan masuk ke Rumah Gadang tanpa izin. Hormati sistem matrilineal.',
    coverImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Rumah_Gadang.jpg/1280px-Rumah_Gadang.jpg',
    latitude: -0.3056,
    longitude: 100.3692,
    nearestGateway: 'Bandara Minangkabau, Padang',
    entryPoint: 'Malaysia → Flight KL-Padang → Drive ke Bukittinggi (2 jam)',
    distanceKm: 90,
    accessLevel: 'MODERATE',
    weatherSummary: 'Tropis dataran tinggi, suhu 18-28°C',
    bestTimeToVisit: 'April-September',
    travelNotes: 'Dari Padang, naik bus atau sewa mobil ke Bukittinggi (2 jam). Jalan berkelok tapi pemandangan indah.',
    safetyNotes: 'Hormati adat lokal. Jalan pegunungan berkelok, hati-hati berkendara.',
  },
  {
    slug: 'palembang-kota-lama',
    name: 'Kota Lama Palembang',
    city: 'Palembang',
    province: 'Sumatera Selatan',
    categoryName: 'Malay Heritage',
    shortDesc: 'Bekas pusat Kerajaan Sriwijaya dan Kesultanan Palembang, kota tertua di Nusantara dengan warisan Melayu yang kaya.',
    culturalMeaning: 'Palembang adalah kota tertua di Indonesia, bekas pusat Kerajaan Sriwijaya yang menguasai perdagangan maritim Asia Tenggara. Warisan Melayu dan Islam masih terasa kuat.',
    localHistory: 'Sriwijaya berdiri abad ke-7 M, menjadi kerajaan maritim terbesar di Asia Tenggara. Kesultanan Palembang Darussalam melanjutkan tradisi ini hingga abad ke-19.',
    malaysiaConnection: 'Sriwijaya memiliki pengaruh besar di Semenanjung Melayu. Banyak tempat di Malaysia yang namanya berasal dari bahasa Melayu Kuno Sriwijaya. Hubungan budaya Sriwijaya-Malaysia masih terlihat hingga kini.',
    localEtiquette: 'Hormati budaya Melayu Palembang. Jangan merusak situs bersejarah.',
    coverImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Jembatan_Ampera_Palembang.jpg/1280px-Jembatan_Ampera_Palembang.jpg',
    latitude: -2.9761,
    longitude: 104.7754,
    nearestGateway: 'Bandara Sultan Mahmud Badaruddin II, Palembang',
    entryPoint: 'Malaysia → Flight KL-Palembang',
    distanceKm: 15,
    accessLevel: 'EASY',
    weatherSummary: 'Tropis, suhu 24-33°C, hujan Nov-Mar',
    bestTimeToVisit: 'April-Oktober',
    travelNotes: 'Dari bandara, naik taksi ke pusat kota (30 menit). Jembatan Ampera dan Sungai Musi menjadi ikon kota.',
    safetyNotes: 'Hati-hati di area sungai. Gunakan transportasi resmi.',
  },
  {
    slug: 'masjid-menara-kudus',
    name: 'Masjid Menara Kudus',
    city: 'Kudus',
    province: 'Jawa Tengah',
    categoryName: 'Islamic History',
    shortDesc: 'Masjid bersejarah dengan menara mirip candi Hindu, simbol akulturasi Islam-Hindu di Jawa.',
    culturalMeaning: 'Masjid Menara Kudus adalah masterpiece akulturasi budaya. Menaranya yang mirip candi Hindu menunjukkan bagaimana Islam beradaptasi dengan budaya lokal Jawa.',
    localHistory: 'Dibangun oleh Sunan Kudus (Ja\'far Shodiq) tahun 1549. Menara bata merah setinggi 18 meter menyerupai candi Majapahit, menunjukkan toleransi dan akulturasi budaya.',
    malaysiaConnection: 'Proses islamisasi di Jawa dan Malaysia memiliki kesamaan: adaptasi budaya lokal, bukan penghapusan. Pendekatan ini membuat Islam mudah diterima di kedua wilayah.',
    localEtiquette: 'Hormati tempat ibadah. Berpakaian sopan. Hormati waktu sholat.',
    coverImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Masjid_Menara_Kudus.jpg/1280px-Masjid_Menara_Kudus.jpg',
    latitude: -6.8047,
    longitude: 110.8405,
    nearestGateway: 'Bandara Ahmad Yani, Semarang',
    entryPoint: 'Malaysia → Flight KL-Semarang → Drive ke Kudus (2 jam)',
    distanceKm: 70,
    accessLevel: 'MODERATE',
    weatherSummary: 'Tropis, suhu 24-33°C, hujan Nov-Mar',
    bestTimeToVisit: 'April-Oktober',
    travelNotes: 'Dari Semarang, naik bus atau sewa mobil ke Kudus (2 jam). Masjid berada di pusat kota Kudus.',
    safetyNotes: 'Hormati tempat ibadah. Jangan memotret saat sholat.',
  },
  {
    slug: 'desa-wae-rebo',
    name: 'Desa Wae Rebo',
    city: 'Ruteng',
    province: 'Nusa Tenggara Timur',
    categoryName: 'Traditional Village',
    shortDesc: 'Desa tersembunyi di pegunungan Flores dengan rumah adat Mbaru Niang berbentuk kerucut, warisan UNESCO.',
    culturalMeaning: 'Wae Rebo adalah salah satu desa paling terisolasi dan autentik di Indonesia. Rumah Mbaru Niang yang berbentuk kerucut adalah arsitektur unik yang telah dilestarikan selama berabad-abad.',
    localHistory: 'Desa ini berada di ketinggian 1.200 mdpl, tersembunyi di pegunungan Flores. Tahun 2012, Wae Rebo mendapat penghargaan UNESCO untuk pelestarian warisan budaya.',
    malaysiaConnection: 'Desa terpencil seperti Wae Rebo menjadi inspirasi bagi pelestarian kampung adat di Malaysia, seperti kampung tradisional di Sabah dan Sarawak.',
    localEtiquette: 'Wajib menginap minimal 1 malam. Hormati adat lokal. Jangan masuk ke rumah tanpa izin. Bawa pakaian hangat.',
    coverImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Wae_Rebo.jpg/1280px-Wae_Rebo.jpg',
    latitude: -8.6333,
    longitude: 120.3667,
    nearestGateway: 'Bandara Frans Sales Lega, Ruteng',
    entryPoint: 'Malaysia → Flight KL-Labuan Bajo → Drive ke Ruteng (6 jam) → Trekking ke Wae Rebo (4 jam)',
    distanceKm: 45,
    accessLevel: 'REMOTE',
    weatherSummary: 'Tropis dataran tinggi, suhu 15-25°C, sering berkabut',
    bestTimeToVisit: 'April-November (hindari musim hujan)',
    travelNotes: 'Perjalanan panjang dan trekking 4 jam dari desa terdekat. Disarankan pakai guide lokal. Bawa pakaian hangat dan obat pribadi.',
    safetyNotes: 'Trekking menantang. Bawa guide lokal. Persiapkan fisik. Bawa obat pribadi dan pakaian hangat.',
  },
  {
    slug: 'selat-malaka-singkawang',
    name: 'Singkawang & Tri Dharma Bumi Raya',
    city: 'Singkawang',
    province: 'Kalimantan Barat',
    categoryName: 'Malay Heritage',
    shortDesc: 'Kota seribu kelenteng, pusat budaya Tionghoa-Indonesia yang unik dengan festival Cap Go Meh terbesar.',
    culturalMeaning: 'Singkawang adalah contoh akulturasi budaya Tionghoa-Melayu-Dayak yang harmonis. Festival Cap Go Meh dengan Tatung (medium spiritual) menjadi warisan budaya unik.',
    localHistory: 'Singkawang telah menjadi pusat perdagangan dan budaya Tionghoa sejak abad ke-18. Kelenteng Tri Dharma Bumi Raya adalah salah satu yang tertua di Kalimantan.',
    malaysiaConnection: 'Banyak orang Tionghoa dari Singkawang yang memiliki keluarga di Kuching, Sarawak. Hubungan dagang dan budaya antara Singkawang-Kuching sangat erat.',
    localEtiquette: 'Hormati kepercayaan lokal. Jangan mengganggu ritual Tatung. Hormati adat Tionghoa dan Dayak.',
    coverImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Singkawang_Temple.jpg/1280px-Singkawang_Temple.jpg',
    latitude: 0.9063,
    longitude: 108.9886,
    nearestGateway: 'Bandara Supadio, Pontianak',
    entryPoint: 'Malaysia → Flight KL-Pontianak → Drive ke Singkawang (2 jam)',
    distanceKm: 140,
    accessLevel: 'MODERATE',
    weatherSummary: 'Tropis, suhu 24-32°C, hujan Okt-Mar',
    bestTimeToVisit: 'Februari (Festival Cap Go Meh) atau April-September',
    travelNotes: 'Dari Pontianak, naik bus atau sewa mobil ke Singkawang (2 jam). Festival Cap Go Meh (15 hari setelah Imlek) adalah waktu terbaik.',
    safetyNotes: 'Hormati ritual Tatung. Jangan memotret terlalu dekat. Hormati adat lokal.',
  },
  {
    slug: 'gili-trawangan-lombok',
    name: 'Gili Trawangan & Warisan Sasak',
    city: 'Lombok Utara',
    province: 'Nusa Tenggara Barat',
    categoryName: 'Maritime Heritage',
    shortDesc: 'Pulau kecil dengan warisan budaya Sasak dan sejarah maritim, perpaduan alam dan tradisi.',
    culturalMeaning: 'Gili Trawangan bukan hanya destinasi wisata, tapi juga menyimpan warisan budaya Sasak dan sejarah maritim masyarakat pesisir Lombok.',
    localHistory: 'Gili Trawangan dulunya tempat pembuangan narapidana. Kini menjadi destinasi wisata terkenal, namun masyarakat Sasak masih mempertahankan tradisi tenun dan adat.',
    malaysiaConnection: 'Masyarakat Sasak memiliki hubungan budaya dengan masyarakat Melayu melalui perdagangan maritim. Banyak elemen budaya yang serupa, terutama dalam tenun dan musik.',
    localEtiquette: 'Hormati budaya Sasak. Jangan masuk ke area privat. Hormati adat lokal.',
    coverImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Gili_Trawangan.jpg/1280px-Gili_Trawangan.jpg',
    latitude: -8.3509,
    longitude: 116.0345,
    nearestGateway: 'Bandara Lombok International',
    entryPoint: 'Malaysia → Flight KL-Lombok → Boat ke Gili Trawangan',
    distanceKm: 35,
    accessLevel: 'MODERATE',
    weatherSummary: 'Tropis, suhu 25-32°C, hujan Nov-Mar',
    bestTimeToVisit: 'April-Oktober',
    travelNotes: 'Dari bandara, naik taksi ke Bangsal (1.5 jam), lalu boat ke Gili Trawangan (30 menit).',
    safetyNotes: 'Hati-hati saat naik turun boat. Gunakan life jacket. Hormati adat lokal.',
  },
];

async function main() {
  console.log('Seeding database...');

  const categories = [
    { name: 'Malay Heritage', slug: 'malay-heritage', description: 'Warisan budaya Melayu', iconName: 'Crown', colorHex: '#e2b96f' },
    { name: 'Islamic History', slug: 'islamic-history', description: 'Sejarah Islam di Nusantara', iconName: 'Mosque', colorHex: '#22c55e' },
    { name: 'Colonial Era', slug: 'colonial-era', description: 'Peninggalan era kolonial', iconName: 'Building', colorHex: '#8b5cf6' },
    { name: 'Traditional Village', slug: 'traditional-village', description: 'Kampung adat dan tradisi', iconName: 'Home', colorHex: '#f59e0b' },
    { name: 'Maritime Heritage', slug: 'maritime-heritage', description: 'Warisan maritim Nusantara', iconName: 'Anchor', colorHex: '#3b82f6' },
  ];

  for (const cat of categories) {
    await prisma.category.upsert({
      where: { slug: cat.slug },
      update: {},
      create: cat,
    });
  }
  console.log(`${categories.length} categories created`);

  for (const dest of destinations) {
    const { categoryName, latitude, longitude, nearestGateway, entryPoint, distanceKm, accessLevel, weatherSummary, bestTimeToVisit, travelNotes, safetyNotes, ...destData } = dest;

    const category = await prisma.category.findUnique({ where: { slug: categoryName.toLowerCase().replace(/ /g, '-') } });
    if (!category) {
      console.log(`Category not found: ${categoryName}`);
      continue;
    }

    const destination = await prisma.destination.upsert({
      where: { slug: dest.slug },
      update: destData,
      create: {
        ...destData,
        categoryId: category.id,
      },
    });

    await prisma.accessCompass.upsert({
      where: { destinationId: destination.id },
      update: {
        nearestGateway,
        entryPoint,
        distanceKm,
        accessLevel,
        weatherSummary,
        bestTimeToVisit,
        travelNotes,
        safetyNotes,
        latitude,
        longitude,
      },
      create: {
        destinationId: destination.id,
        nearestGateway,
        entryPoint,
        distanceKm,
        accessLevel,
        weatherSummary,
        bestTimeToVisit,
        travelNotes,
        safetyNotes,
        latitude,
        longitude,
      },
    });

    console.log(`✓ ${dest.name}`);
  }

  console.log(`\n${destinations.length} destinations seeded!`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
