services:
  postgres:
    image: postgres:16
    container_name: warisan-postgres
    restart: always
    environment:
      POSTGRES_USER: warisan_user
      POSTGRES_PASSWORD: StrongPassword!123
      POSTGRES_DB: warisan_link
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
